
import pandas as pd
import os

class OpenWAMOutputParser:
    """
    Parses output files (.DAT) generated by OpenWAM.
    """
    
    @staticmethod
    def parse_avg_dat(filepath: str) -> pd.DataFrame:
        """
        Parses the AVG.DAT file containing average results per cycle/step.
        
        Args:
            filepath: Path to the .DAT file
            
        Returns:
            pd.DataFrame containing the simulation results
        """
        if not os.path.exists(filepath):
            raise FileNotFoundError(f"Output file not found: {filepath}")
            
        try:
            # OpenWAM output files are tab-separated
            # The header line often starts with a tab or has messy spacing
            # We'll read it using pandas read_csv with sep='\t'
            
            # Check first few lines to determine header row
            with open(filepath, 'r') as f:
                lines = f.readlines()
                
            header_row = 0
            for i, line in enumerate(lines):
                if "rpm" in line or "RPM" in line or "Engine Speed" in line:
                    header_row = i
                    break
            
            # Read DataFrame
            df = pd.read_csv(filepath, sep='\t', header=header_row)
            
            # Clean column names
            # Remove empty columns (OpenWAM often leads/trails with tabs)
            df = df.dropna(axis=1, how='all')
            
            # Strip whitespace from column names
            df.columns = [c.strip() for c in df.columns]
            
            return df
            
        except Exception as e:
            raise ValueError(f"Failed to parse output file: {str(e)}")

    @staticmethod
    def extract_ve_curve(df: pd.DataFrame) -> pd.DataFrame:
        """
        Extracts just the RPM and Volumetric Efficiency columns.
        Normalizes column names if needed.
        """
        # Identify RPM column
        rpm_col = next((c for c in df.columns if "Speed" in c or "Regimen" in c), None)
        # Identify VE column
        ve_col = next((c for c in df.columns if "Vol. Eff" in c or "Rendimiento" in c), None)
        
        if rpm_col and ve_col:
            return df[[rpm_col, ve_col]].sort_values(by=rpm_col)
            
        return pd.DataFrame()
