
import pandas as pd
import os
import re
import statistics

class OpenWAMOutputParser:
    """
    Parses output files (.DAT) generated by OpenWAM.
    """
    
    @staticmethod
    def parse_avg_dat(filepath: str) -> pd.DataFrame:
        """
        Parses the AVG.DAT file containing average results per cycle/step.
        
        Args:
            filepath: Path to the .DAT file
            
        Returns:
            pd.DataFrame containing the simulation results
        """
        if not os.path.exists(filepath):
            raise FileNotFoundError(f"Output file not found: {filepath}")
            
        try:
            # OpenWAM output files are tab-separated
            # The header line often starts with a tab or has messy spacing
            # We'll read it using pandas read_csv with sep='\t'
            
            # Check first few lines to determine header row
            with open(filepath, 'r') as f:
                lines = f.readlines()
                
            header_row = 0
            for i, line in enumerate(lines):
                if "rpm" in line or "RPM" in line or "Engine Speed" in line:
                    header_row = i
                    break
            
            # Read DataFrame
            df = pd.read_csv(filepath, sep='\t', header=header_row)
            
            # Clean column names
            # Remove empty columns (OpenWAM often leads/trails with tabs)
            df = df.dropna(axis=1, how='all')
            
            # Strip whitespace from column names
            df.columns = [c.strip() for c in df.columns]
            
            return df
            
        except Exception as e:
            raise ValueError(f"Failed to parse output file: {str(e)}")

    @staticmethod
    def extract_ve_curve(df: pd.DataFrame) -> pd.DataFrame:
        """
        Extracts just the RPM and Volumetric Efficiency columns.
        Normalizes column names if needed.
        """
        # Identify RPM column
        rpm_col = next((c for c in df.columns if "Speed" in c or "Regimen" in c), None)
        # Identify VE column
        ve_col = next((c for c in df.columns if "Vol. Eff" in c or "Rendimiento" in c), None)
        
        if rpm_col and ve_col:
            return df[[rpm_col, ve_col]].sort_values(by=rpm_col)

    # ---- cylinder-balance gate (Stage 42) ---------------------------------
    # The eq-tube resonance can, in narrow throttle/rpm islands, drive ONE
    # cylinder to collapse (~0) or blow up (>>) while the rest are fine. The
    # engine-average VE then reads garbage. There is no deck fix that removes
    # this without distorting the validated VE-rpm SHAPE, so the optimiser must
    # instead DETECT and REJECT such points. This parses the per-cylinder
    # trapped mass from the VEDIAG diagnostic (run with OPENWAM_VEDIAG=1) and
    # judges the last converged cycle by how far the worst cylinder sits from
    # the fleet MEDIAN (robust to one outlier).
    @staticmethod
    def cylinder_balance(stdout: str, tol: float = 0.20, n_cyl: int = 6) -> dict:
        """Return {valid, spread, ve_cyl, n} from VEDIAG per-cylinder Mtrap.

        valid  -> True if every cylinder is within `tol` (frac) of the median
                  (i.e. no collapse/blow-up); the optimiser should drop the
                  operating point when valid is False.
        spread -> max |m_i - median| / median over the last full cycle.
        """
        ms = [float(x) for x in re.findall(r"VEDIAG Cyl:\d+ .*?Mtrap:([0-9.]+) g", stdout)]
        if len(ms) < n_cyl:
            return {"valid": False, "spread": float("nan"), "ve_cyl": None,
                    "n": len(ms), "reason": "insufficient VEDIAG data"}
        seg = ms[-n_cyl:]                       # last full cycle
        med = statistics.median(seg)
        if med <= 0:
            return {"valid": False, "spread": float("inf"), "ve_cyl": seg,
                    "n": len(ms), "reason": "median trapped mass <= 0"}
        spread = max(abs(m - med) for m in seg) / med
        return {"valid": spread <= tol, "spread": spread, "ve_cyl": seg,
                "n": len(ms), "reason": "" if spread <= tol else "cylinder maldistribution"}

        return pd.DataFrame()
