
import pandas as pd
import os
import re
import math
import statistics

class OpenWAMOutputParser:
    """
    Parses output files (.DAT) generated by OpenWAM.
    """
    
    @staticmethod
    def parse_avg_dat(filepath: str) -> pd.DataFrame:
        """
        Parses the AVG.DAT file containing average results per cycle/step.
        
        Args:
            filepath: Path to the .DAT file
            
        Returns:
            pd.DataFrame containing the simulation results
        """
        if not os.path.exists(filepath):
            raise FileNotFoundError(f"Output file not found: {filepath}")
            
        try:
            # OpenWAM output files are tab-separated
            # The header line often starts with a tab or has messy spacing
            # We'll read it using pandas read_csv with sep='\t'
            
            # Check first few lines to determine header row
            with open(filepath, 'r') as f:
                lines = f.readlines()
                
            header_row = 0
            for i, line in enumerate(lines):
                if "rpm" in line or "RPM" in line or "Engine Speed" in line:
                    header_row = i
                    break
            
            # Read DataFrame
            df = pd.read_csv(filepath, sep='\t', header=header_row)
            
            # Clean column names
            # Remove empty columns (OpenWAM often leads/trails with tabs)
            df = df.dropna(axis=1, how='all')
            
            # Strip whitespace from column names
            df.columns = [c.strip() for c in df.columns]
            
            return df
            
        except Exception as e:
            raise ValueError(f"Failed to parse output file: {str(e)}")

    @staticmethod
    def extract_ve_curve(df: pd.DataFrame) -> pd.DataFrame:
        """
        Extracts just the RPM and Volumetric Efficiency columns.
        Normalizes column names if needed.
        """
        # Identify RPM column
        rpm_col = next((c for c in df.columns if "Speed" in c or "Regimen" in c), None)
        # Identify VE column
        ve_col = next((c for c in df.columns if "Vol. Eff" in c or "Rendimiento" in c), None)
        
        if rpm_col and ve_col:
            return df[[rpm_col, ve_col]].sort_values(by=rpm_col)

    # ---- cylinder-balance gate (Stage 42) ---------------------------------
    # The eq-tube resonance can, in narrow throttle/rpm islands, drive ONE
    # cylinder to collapse (~0) or blow up (>>) while the rest are fine. The
    # engine-average VE then reads garbage. There is no deck fix that removes
    # this without distorting the validated VE-rpm SHAPE, so the optimiser must
    # instead DETECT and REJECT such points. This parses the per-cylinder
    # trapped mass from the VEDIAG diagnostic (run with OPENWAM_VEDIAG=1) and
    # judges the last converged cycle by how far the worst cylinder sits from
    # the fleet MEDIAN (robust to one outlier).
    @staticmethod
    def cylinder_balance(stdout: str, tol: float = 0.20, n_cyl: int = 6) -> dict:
        """Return {valid, spread, ve_cyl, n} from VEDIAG per-cylinder Mtrap.

        valid  -> True if every cylinder is within `tol` (frac) of the median
                  (i.e. no collapse/blow-up); the optimiser should drop the
                  operating point when valid is False.
        spread -> max |m_i - median| / median over the last full cycle.
        """
        ms = [float(x) for x in re.findall(r"VEDIAG Cyl:\d+ .*?Mtrap:([0-9.]+) g", stdout)]
        if len(ms) < n_cyl:
            return {"valid": False, "spread": float("nan"), "ve_cyl": None,
                    "n": len(ms), "reason": "insufficient VEDIAG data"}
        seg = ms[-n_cyl:]                       # last full cycle
        med = statistics.median(seg)
        if med <= 0:
            return {"valid": False, "spread": float("inf"), "ve_cyl": seg,
                    "n": len(ms), "reason": "median trapped mass <= 0"}
        spread = max(abs(m - med) for m in seg) / med
        return {"valid": spread <= tol, "spread": spread, "ve_cyl": seg,
                "n": len(ms), "reason": "" if spread <= tol else "cylinder maldistribution"}

    # ---- convergence gate (Stage 36 / §3.6) -------------------------------
    @staticmethod
    def convergence(stdout: str, m_ref_mg: float, last_n: int = 5,
                    slope_tol: float = 0.3) -> dict:
        """Per-cell convergence from the 'Trapped mass:' cycle series.

        Ports ve_converged_robust.py: parse every 'Trapped mass: X (g)', drop
        consecutive duplicates (each IVC is printed twice), filter blow/collapse,
        convert to VE% via ``m_ref_mg`` (theoretical trapped mass at VE=100 %, in
        mg), and judge convergence by the slope of the last ``last_n`` cycles
        (|dVE/dcycle| < ``slope_tol``).
        """
        ms = [float(x) for x in re.findall(r"Trapped mass:\s+([0-9.eE+-]+)\s+\(g\)", stdout)]
        dedup = []
        for v in ms:
            if not dedup or abs(v - dedup[-1]) > 1e-9:
                dedup.append(v)
        good = [m for m in dedup if 1e-4 < m < 5.0]
        if not good:
            return {"converged": False, "slope": None, "cyc": 0,
                    "ve_series": [], "ve_last": None, "blew_up": True}
        if m_ref_mg and m_ref_mg > 0:
            ve_series = [(m * 1000.0 / m_ref_mg) * 100.0 for m in good]
        else:
            ve_series = []
        n = len(ve_series)
        seg = ve_series[-last_n:] if n >= 2 else ve_series
        slope = float("nan")
        if len(seg) >= 2:
            xs = list(range(len(seg)))
            mx = sum(xs) / len(xs)
            my = sum(seg) / len(seg)
            denom = sum((x - mx) ** 2 for x in xs)
            slope = (sum((x - mx) * (y - my) for x, y in zip(xs, seg)) / denom) if denom else float("nan")
        converged = len(seg) >= 2 and not math.isnan(slope) and abs(slope) < slope_tol
        blew_up = bool(ve_series and max(ve_series[-3:]) > 300.0)
        return {"converged": bool(converged),
                "slope": (None if math.isnan(slope) else round(slope, 4)),
                "cyc": n, "ve_series": ve_series,
                "ve_last": (ve_series[-1] if ve_series else None),
                "blew_up": blew_up}
